/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import editoriala.ManPublica;
import jerarquiaHerencia.Publicaciones;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import jerarquiaHerencia.Libro;
import jerarquiaHerencia.Revista;

/**
 *
 * @author alexa
 */
public class Tabla extends javax.swing.JFrame {

    static ArrayList<Publicaciones> Arrpublica = new ArrayList<Publicaciones>();
    ManPublica mp = new ManPublica();

    /**
     * Creates new form Tabla
     */
    public Tabla() {
        initComponents();
        llenarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tipo", "Titulo", "Precio", "No.Pag", "ISBN", "Autor", "Edicion", "ISSN", "Numero", "Editor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        Bienvenida bi = new Bienvenida();
        bi.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void llenarTabla() {
        DefaultTableModel modelDefault = new DefaultTableModel(new String[]{"Tipo", "Titulo", "Precio", "No.Pag", "ISBN", "Autor", "Edicion", "ISSN", "Numero", "Editor"}, ManPublica.Arrpublica.size());
        jTable1.setModel(modelDefault);

        TableModel modeldatos = jTable1.getModel();
        for (int i = 0; i < ManPublica.Arrpublica.size(); i++) {

            Publicaciones pu = ManPublica.Arrpublica.get(i);
            modeldatos.setValueAt(pu.getTitulo(), i, 1);
            modeldatos.setValueAt(pu.getPrecio(), i, 2);
            modeldatos.setValueAt(pu.getNoPag(), i, 3);
            if (pu instanceof Libro) {
                Libro book = new Libro();
                book = (Libro) pu;
                modeldatos.setValueAt("Libro", i, 0);
                modeldatos.setValueAt(book.getISBN(), i, 4);
                modeldatos.setValueAt(book.getAutor(), i, 5);
                modeldatos.setValueAt(book.getEdicion(), i, 6);
            } else if (pu instanceof Revista) {
                Revista maga = new Revista();
                maga = (Revista) pu;
                modeldatos.setValueAt("Revista", i, 0);
                modeldatos.setValueAt(maga.getISSN(), i, 7);
                modeldatos.setValueAt(maga.getNumero(), i, 8);
            } else if (pu instanceof jerarquiaHerencia.Periodico) {
                jerarquiaHerencia.Periodico peri = new jerarquiaHerencia.Periodico();
                peri = (jerarquiaHerencia.Periodico) pu;
                modeldatos.setValueAt("Periodico", i, 0);
                modeldatos.setValueAt(peri.getEditor(), i, 9);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
